export { OperationResponseDto } from 'src/storage/dtos/operation_response.dto'
export { UploadNewFileRequestDto } from 'src/storage/dtos/uploadNewFileRequest.dto'
export { InternalOperationDto } from 'src/storage/dtos/internal_operation.dto'
export { ImageDeliveryDto } from 'src/storage/dtos/image_delivery.dto'
export { DeleteFileRequestDto } from 'src/storage/dtos/deleteFileRequest.dto'